[project]
name = "termagent"
version = "0.1.0"
description = "A Python package for terminal agent functionality"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]
